include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore

linter:
  rules:
    avoid_print: false
    use_key_in_widget_constructors: false
    prefer_const_constructors: false
    constant_identifier_names: false
    prefer_const_literals_to_create_immutables: false
    sized_box_for_whitespace: false
    file_names: false
    curly_braces_in_flow_control_structures: false
    implementation_imports: false
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
